name: .NET Standard Library Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: FluentMailMessageBuilder.sln                     
      Test_Project_Path: FluentMailMessageBuilder.test.csproj                        

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Nuget Library Deploy
  # You may pin to the exact commit or the version.
  # uses: EasyDesk/job-nuget-library-deploy@35692f3e098d0b3bed293b808da55b7f7c4b93c5
      uses: EasyDesk/job-nuget-library-deploy@v1.0.0
      with:
    # .NET version to be used (e.g. 5.x or 5.0.x).
        dotnet-version:  6.0.x
    # The Nuget API key.
        nuget-api-key: ${{secrets.NUGET_KEY}}
